### ISSUE TITLE
The web interface of covenant goes straight to the login page 

### ISSUE THREAD

**Issue by Karigar4039** [isaudits/docker-covenant#1]
i am unable to register the initial account please help. I am on the login page and I dont have username or password because the website came straight to the login page

**Comment by mcjon3z** [comment]
default environment variable values which include the admin username and password are specified in the dockerfile (https://github.com/isaudits/docker-covenant/blob/master/Dockerfile) so those will be the values if you do not pass your own via docker run command or .env file.

**Comment by Karigar4039** [comment]
Thanks. 🙏👍
